[package]
name = "blahaj"
version = "0.2.1"
license = "MIT"
authors = ["Isabel Roses <isabel@isabelroses.com>"]
description = "the resident discord bot of :3"
readme = "README.md"
homepage = "https://github.com/isabelroses/blahaj"
repository = "https://github.com/isabelroses/blahaj"
keywords = ["discord", "bot", "serenity"]
edition = "2021"

[dependencies]
bottomify = "1.2.0"
color-eyre = "0.6.3"
dotenv = "0.15.0"
humantime = "2.2.0"
kittysay = "0.8.0"
nixpkgs-track_lib = "0.2.0"
poise = "0.6.1"
rand = "0.9.0"
regex = "1.11.1"
serenity = "0.12.4"

[dependencies.serde]
version = "1.0.219"
features = ["derive"]

[dependencies.reqwest]
version = "0.12.15"
features = ["json"]

[dependencies.tokio]
version = "1.44.2"
features = ["macros", "rt-multi-thread"]

[lints.clippy]
all = "warn"
pedantic = "warn"
unreadable_literal = { level = "allow", priority = 1 }
