[package]
name = "blahaj"
version = "0.2.0"
license = "MIT"
authors = ["Isabel Roses <isabel@isabelroses.com>"]
description = "the resident discord bot of :3"
readme = "README.md"
homepage = "https://github.com/isabelroses/blahaj"
repository = "https://github.com/isabelroses/blahaj"
keywords = ["discord", "bot", "serenity"]
edition = "2021"

[dependencies]
bottomify = "1.2.0"
color-eyre = "0.6.3"
dotenv = "0.15.0"
humantime = "2.1.0"
poise = "0.6.1"
rand = "0.8.5"
regex = "1.10.5"
reqwest = "0.12.4"
serenity = "0.12.2"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }

[lints.clippy]
all = "warn"
pedantic = "warn"
